homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Australia/Melbourne
  # Include Packages
  packages: !include_dir_named packages
  whitelist_external_dirs:
   - /tmp
   - /share
    

# Customizations
  customize_domain: {}
  customize_glob: {}

# Enables the frontend
http:
  base_url: !secret base_url

# Enables Default Home Assistant Components
default_config:

# Enables Person Component
person:

# Enables System Health
system_health:

panel_iframe:
# Hass Configurator Panel
  configurator:
    title: IDE
    icon: mdi:wrench
    url: !secret ide_url
  terminal:
    title: Terminal
    icon: mdi:console-line
    url: !secret terminal_url

panel_custom:
# Floorplan Panel
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

# Checks for available updates
updater:

# Discover some devices automatically
discovery:
  ignore:
  - netgear_router

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# Add Configuration Panel
config:

logbook:
  exclude:
    entities:
      - sensor.uptime
      - sensor.time
      - sensor.date
      - sensor.date_2
      - sensor.date_time
      - sensor.time_date
      - sensor.nzbget_speed


# Track the sun
sun:

# Text to speech
tts:
- platform: amazon_polly
  aws_access_key_id: !secret aws_access_key_ID
  aws_secret_access_key: !secret aws_secret_access_key
  text_type: ssml
  voice: Joanna

# Purge Database Interval and MariaDB
recorder:
  db_url: !secret mariadb_url
  purge_interval: 1
  purge_keep_days: 14

sensor:
- platform: time_date
  display_options:
    - 'time'
    - 'date'

# IFTTT Key
ifttt:
  key: !secret ifttt_api

# iOS App
ios:

# Device Tracking
# Zigbee2mqtt Discovery
# MQTT (Local Broker)
mqtt:
  discovery: true
  broker: !secret local_mqtt_broker
  port: !secret local_mqtt_port
  username: !secret local_mqtt_username
  password: !secret local_mqtt_password
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'


# Logitech Harmony Living Room
remote:
  - platform: harmony
    name: !secret harmony_name
    host: !secret harmony_ip
    activity: Watch TV